trigger:
- master

pr:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: linux-build.yml

# - job: macOS
#   pool:
#     vmImage: 'macOS-10.15'
#   steps:
#   - template: mac-build.yml

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: windows-build.yml